language: php

matrix:
  include:
    php:
      - 5.3
      - 5.4
      - 5.5
      - 5.6
      - 7.0
      - 7.1
      - hhvm
    dist: trusty
  allow_failures:
    php:
      - hhvm

install: travis_retry composer update --no-interaction

script: vendor/bin/phpunit --verbose

